Add some statement for D05 SR-IOV issue
Linaro/documentation pull request #60
Opened 2017-12-04 10:49 UTC by xin3liang

Add some statement for D05 SR-IOV issue.

2017-12-04 10:56 UTC, rosly requested changes
I would suggest that this should be mentioned as separate bullet point, with more explicit statement that "D05 does not support SRIOV and IOMMU features for this release, which influence DPDK functionality on D05 platform"

2017-12-04 11:12 UTC, gemagomez commented on Reference-Platform/Platforms/Enterprise/ReleaseNotes-17.12.md
> +- [3169](https://bugs.linaro.org/show_bug.cgi?id=3169) DPDK: can't enable sr-iov on D05 with Intel 82599. SMMU is not enabled and SR-IOV is not enabled well on D05.
Please, move this to the D05 section, rather than DPDK. Then remove DPDK from the title of the bug, since this is wider than just DPDK.

2017-12-05 01:13 UTC, xin3liang commented
Had moved this part to D05 section.

2017-12-05 07:48 UTC, gemagomez commented
Looks good to me, thanks!

2017-12-05 09:24 UTC, merged